### ISSUE TITLE
actions/checkout@v3で何か事故ってるよー

### ISSUE THREAD

**Issue by east-or-est** [east-or-est/github_actions_test#1]
後日改修してね！

**Comment by east-or-est** [comment]
とりあえずエラー部分を一旦取り除いてテスト通過を確認しました。
```
      # チェックアウト
      - uses: actions/checkout@v3
        with:
          repository: github_actions_test/hoge
          path: hoge
```
